// Copies the IDL generated by `anchor build` into the frontend.
import { copyFileSync, existsSync } from "node:fs";
const src = new URL("../../target/idl/trust_bridge.json", import.meta.url);
const dst = new URL("../src/idl/trust_bridge.json", import.meta.url);
if (!existsSync(src)) {
  console.error("target/idl/trust_bridge.json not found. Run `anchor build` in the repo root first.");
  process.exit(1);
}
copyFileSync(src, dst);
console.log("IDL synced to app/src/idl/trust_bridge.json");
